POST http://localhost:8080/bookings
Content-Type: application/json

{
  "booking": {
    "name": "John",
    "date": "2006-Jan-03"
  }
}

###
GET http://localhost:8080/classes
Accept: application/json

###
POST http://localhost:8080/classes
Content-Type: application/json

{
  "class": {
    "name": "test1",
    "start_date": "2006-Jan-02",
    "end_date": "2006-Jan-04",
    "capacity": 8
  }
}

###

